name: Build RedPill DSM loader

on: workflow_dispatch

jobs:
  redpill:
    runs-on: ubuntu-latest
    name: Build RedPill lkm and load
    steps:
      - uses: actions/checkout@v2.1.0
        name: checkout src
        id: checkout
        with:
          submodules: 'true'
      - name: Build RS4021xs+ 7.0.1
        id: build-ds3622xsp-70
        run: |
            bash build-rs4021xsp-7.0.1.sh
      - name: Archive RS4021xs+ 7.0.1 loader image
        uses: actions/upload-artifact@v2
        with:
          name: redpill-RS4021xs+_7.0.1-loader
          path: output/redpill-RS4021xs+_7.0*.img
